apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user-deployment
  namespace: kube-honduras
  labels:
    app: ms-user-honduras
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user-honduras
  template:
    metadata:
      labels:
        app: ms-user-honduras
    spec:
      containers:
        - env:
            - name: CONEXION_MONGO
              valueFrom:
                secretKeyRef:
                  name: secretsipac
                  key: MONGO_CONNECTION
            - name: ITERATION
              value: "33"
            - name: KEY_LENGTH
              value: "256"
            - name: MS-NOTIFY
              value: http://ms-notify:8084
            - name: PORT_SERVER
              value: "8085"
            - name: SECRET
              value: mysecret
            - name: RHOST
              value: redis-service
            - name: MS-BLOCKCHAIN
              value: http://ms-blockchain:8092
            - name: MS-API-GATEWAY
              value: http://ms-security:8090/
            - name: PRIVATE_KEY_BACKEND
              valueFrom:
                secretKeyRef:
                  name: secretsipac
                  key: PRIVATE_KEY_BACKEND
          image: {{DOCKER_IMAGE_TAG}}
          name: ms-user
          # resources:
          #   requests:
          #     cpu: 120m
          #     memory: 128Mi
          #   limits:
          #     cpu: 300m
          #     memory: 256Mi
      hostname: ms-user
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ms-user
  namespace: kube-honduras
  labels:
    app: ms-user-honduras
spec:
  selector:
    app: ms-user-honduras
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      name: http
  type: NodePort
